webtalk_init -webtalk_dir C:/Users/jiang/OneDrive/Vivado/Lab4/Prac/Prac/Prac.sim/sim_1/behav/xsim/xsim.dir/tb_lab4_Practice_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 13 16:47:43 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "afc55e78-a0bc-401d-8a9d-7f95bbe165d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "330d0a75c5fc4b64a234bc082fb52635" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8680_KB" -context "xsim\\usage"
webtalk_transmit -clientid 149053666 -regid "" -xml C:/Users/jiang/OneDrive/Vivado/Lab4/Prac/Prac/Prac.sim/sim_1/behav/xsim/xsim.dir/tb_lab4_Practice_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jiang/OneDrive/Vivado/Lab4/Prac/Prac/Prac.sim/sim_1/behav/xsim/xsim.dir/tb_lab4_Practice_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jiang/OneDrive/Vivado/Lab4/Prac/Prac/Prac.sim/sim_1/behav/xsim/xsim.dir/tb_lab4_Practice_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
